version:  '1'
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        API_SERVICE_URL: ${API_SERVICE_URL}
        CURRENT_YEAR: ${CURRENT_YEAR}
    restart: always
    ports:
      - 3000:80
  api:
    build: ./server
    restart: always
    depends_on:
      - mongo
    ports:
      - ${API_PORT}:5000
    environment:
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
      PORT: 5000
  mongo:
    image: mongo:4.4.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - ${ME_PORT}:8081
    environment:
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
