version:  '1'
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - '3000:80'
  api:
    build: ./server
    restart: always
    depends_on:
      - mongo
    ports:
      - '3001:5000'
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      PORT: 5000
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
