services:
  api:
    build: ./server
    restart: always
    depends_on:
      - mongo
    ports:
      - ${API_PORT}:5000
    environment:
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
      PORT: 5000
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
